### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by bilo-io** [ivansams/GuidRandomiser#3]
This is not an issue per se, but could you provide a code example of the command and `example.json` as the file? This would make it more readable, making your GuidRandomiser more accessible. And where does the output go?

**Comment by ivansams** [comment]
Thanks @bilo-io - I have merged in some better instructions as well as example files so you can see the effect. The output is saved in the same directory as the input file just with `.rnd` appended to the filename. Hope you find the GuidRandomiser helpful!
